# Generated by Django 3.2.20 on 2023-09-26 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0003_genesymbol_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genefavorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='genefavorite_last_view',
            name='genefavorite',
        ),
        migrations.RemoveField(
            model_name='genefavorite_last_view',
            name='user',
        ),
        migrations.DeleteModel(
            name='Gene',
        ),
        migrations.DeleteModel(
            name='GeneFavorite',
        ),
        migrations.DeleteModel(
            name='GeneFavorite_Last_View',
        ),
    ]
