###
# Copyright 2017, Institute for Systems Biology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

runtime: custom
env: flex
service: default
api_version: 1

resources:
  cpu: 4
  memory_gb: 20
  disk_size_gb: 40

builtins:
- appstats: on
- deferred: on

beta_settings:
    cloud_sql_instances: isb-cgc:us-central1:prod-v2

env_variables:
  DJANGO_SETTINGS_MODULE: 'isb_cgc.settings'

network:
  name: solr
  instance_tag: isb-cgc-webapp

skip_files:
- python-su.sh
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\.(?!env).*$
- ^google-cloud-sdk/.*$
- ^google_appengine\.zip$
- ^(.*/)?.*\.sql$
- ^venv/.*$
- ^static/.*$
