runtime: custom
module: default
api_version: 1
threadsafe: true
vm: true

resources:
  cpu: .5
  memory_gb: 2.2

builtins:
- django_wsgi: on
- remote_api: on
- appstats: on
- deferred: on

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/imgfavicon.ico
- url: /static
  static_dir: static
- url: /_ah/spi/.*
  script: cgc_api.APPLICATION
- url: /remoteapi.*
  script: google.appengine.ext.remote_api.handler.application
  login: admin
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin
- url: /.*
  script: main.application
- url: /static/admin
  static_dir: static/admin
  expiration: 0
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

env_variables:
  GAE_TMP_FORCE_REUSE_API_CONNECTION: true
  DJANGO_SETTINGS_MODULE: 'GenespotRE.settings'
  SETTINGS_VERSION: 'uat'