# Generated by Django 2.2.13 on 2021-01-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_version', models.CharField(default='1.0.0', max_length=32)),
                ('app_name', models.CharField(blank=True, max_length=128)),
                ('app_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
