# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-29 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='log_transf_x',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plot',
            name='log_transf_y',
            field=models.BooleanField(default=False),
        ),
    ]
