# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0002_auto_20170828_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viz_perms',
            name='perm',
            field=models.CharField(choices=[('READER', 'Reader'), ('OWNER', 'Owner')], default='READER', max_length=10),
        ),
    ]
