# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_auto_20180629_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2024)),
                ('vm_username', models.CharField(max_length=20)),
                ('zone', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('gcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.GoogleProject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
