# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-16 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Key')),
                ('value', models.BooleanField(default=False, verbose_name='Value')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
