# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-01 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0005_workbook_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet_gene',
            name='type',
            field=models.CharField(default=b'gene', max_length=16),
        ),
    ]
