# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0006_worksheet_gene_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook_perms',
            name='perm',
            field=models.CharField(choices=[('READER', 'Reader'), ('OWNER', 'Owner')], default='READER', max_length=10),
        ),
        migrations.AlterField(
            model_name='worksheet_gene',
            name='type',
            field=models.CharField(default='gene', max_length=16),
        ),
    ]
