# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0002_variable_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablefavorite',
            name='last_date_saved',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='variablefavorite_last_view',
            name='last_view',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
