# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-02 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0003_auto_20160614_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablefavorite',
            name='build',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
